### ISSUE TITLE
Pulsating Black Hole Doesn't Have Recipe

### ISSUE THREAD

**Issue by ItsWolphie** [AllTheMods/atm9nf#112]
I went to see what the recipe of the Pulsating Black Hole and found out no recipe was attached to it

**Comment by TheBedrockMaster** [comment]
Yeah, same problem here.

**Comment by Astronaut200** [comment]
Yeah, I have same issue on 0.1.15, hopefully they fix soon.

**Comment by john-sp** [comment]
I submitted the fix in #115, there is other things that should be merged from the main repo too, like the quest book. Everything looks done in the main ATM9 repo

**Comment by nMoodC** [comment]
Hi, its not fixed yet. Neither of versions 0.1.15 or 0.1.16 fixed this. Apotheosis changed ,,Vials of expulsion", therefore, pulsating black hole recipe is still broken and not available.

**Comment by TheBedrockMaster** [comment]
> Hi, its not fixed yet. Neither of versions 0.1.15 or 0.1.16 fixed this. Apotheosis changed ,,Vials of expulsion", therefore, pulsating black hole recipe is still broken and not available.

This time Thermal Extra broke it, the Apotheosis one was fixed.

**Comment by Kupanfu** [comment]
If you want a temporary fix till it gets updated you can do the following.
Open your ATM9 folder and navigate down to kubejs/server_scripts/modpack folder.
Open att_items in a word editor
Find the section for the pulsating black hole and edit the line for the thermal extra item.
it should be abyssal_rf_coil_xfer_augment instead of rf_coil_xfer_augment_5 (at least if my guess is right)
and voila the recipe should now be viewable in jei

**Comment by Hibanan** [comment]
Tried the above hotfix to no avail. No JEI or quest so I’m assuming the item ID is wrong.

**Comment by TheBedrockMaster** [comment]
> Tried the above hotfix to no avail. No JEI or quest so I’m assuming the item ID is wrong.

Copy the recipe fix from this PR. https://github.com/AllTheMods/atm9nf/pull/125
